spin_manifest_version = "1"
authors = ["mhyoo"]
description = ""
name = "wasm_poc"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "wasm-poc"
source = "main.wasm"
allowed_http_hosts = [raw.githubusercontent.com]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
